#### 0. Import the numpy package under the name `np`

In [1]:
import numpy as np

#### 0. Print the numpy version and the configuration

In [ ]:
print()

#### 1. Create a null vector of size 10

In [4]:
Z = np.zeros(10)
print(Z)
print(Z[0])
print(type(Z[0]))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0
<class 'numpy.float64'>


In [5]:
print(np.empty(10, dtype=int))
print(np.empty(10))

[41840336        0        0        0        0        0        0        0
        0        0]
[2.06718726e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000]


In [6]:
# empty, unlike zeros, does not set the array values to zero, 
# and may therefore be marginally faster. 
# On the other hand, it requires the user to manually set 
# all the values in the array, and should be used with caution.

#### 2. How to find the memory size of any array

In [7]:
Z = np.zeros((10,10))
print(Z.size)
print(Z.itemsize)
print("%d bytes" % (Z.size * Z.itemsize))

100
8
800 bytes


In [9]:
Z.nbytes

800

#### 4. Create a null vector of size 10 but the fifth value which is 1 

In [8]:
Z = np.zeros(4)
Z[4] = 1
print(Z)

IndexError: index 4 is out of bounds for axis 0 with size 4

#### 5. Create a vector with values ranging from 10 to 49

In [11]:
Z = np.arange(10,20)
print(Z)
Y = np.linspace(10,19,10)
print(Y)
X = np.linspace(10,20,10,endpoint=False)
print(X)
W = np.arange(10,20,1)
print(W)

[10 11 12 13 14 15 16 17 18 19]
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
[10 11 12 13 14 15 16 17 18 19]


#### 6. Reverse a vector (first element becomes last)

In [12]:
Z = np.arange(5)
print(Z[::-1])
print(np.fliplr([Z])[0])
print(np.flipud(Z))
print(Z)

[4 3 2 1 0]
[4 3 2 1 0]
[4 3 2 1 0]
[0 1 2 3 4]


In [13]:
Z[:-1]

array([0, 1, 2, 3])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
Z = np.arange(0,8).reshape(3, 3)
print(Z)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [15]:
np.linspace(0,9,9).reshape(3,3)

array([[0.   , 1.125, 2.25 ],
       [3.375, 4.5  , 5.625],
       [6.75 , 7.875, 9.   ]])

#### 8. Find indices of non-zero elements from [1,2,0,0,4,0]

In [20]:
nz = np.nonzero([1,2,0,0,-4,0])
print(nz[0])

[0 1 4]


#### 9. Create a 3x3 identity matrix

In [18]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
print(np.ones(3))
print(np.ones(9).reshape(3,3))

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 10. Create a 3x3x3 array with random values

In [24]:
Z = np.random.random((3,3,3))
print(Z)
Y = np.random(3,3,3)
print(Y)

[[[0.82234985 0.1708726  0.12737585]
  [0.07268361 0.29493062 0.17213531]
  [0.25828679 0.42765954 0.24825319]]

 [[0.66756908 0.51428981 0.49183928]
  [0.93375715 0.48223975 0.81003034]
  [0.16792008 0.49695371 0.68347898]]

 [[0.23928701 0.53238213 0.89494237]
  [0.79509965 0.76174021 0.23628907]
  [0.75848497 0.0514412  0.340936  ]]]


TypeError: 'module' object is not callable

In [22]:
np.random.random(27).reshape(3,3,3)

array([[[0.92163035, 0.66854666, 0.9723607 ],
        [0.69566602, 0.5218822 , 0.49057649],
        [0.14094522, 0.19025719, 0.39644165]],

       [[0.48781892, 0.33784962, 0.17981566],
        [0.06821045, 0.55741088, 0.66548499],
        [0.05309234, 0.17058916, 0.02466785]],

       [[0.93419052, 0.56046351, 0.17765865],
        [0.3600626 , 0.05784608, 0.49471203],
        [0.7848808 , 0.0836632 , 0.26006689]]])

#### 0. Create a 10x10 array with random values and find the minimum and maximum values

In [25]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0009389952441333227 0.9943520428406986


#### 0. Create a random vector of size 30 and find the mean value

#### 11. Create a 2d array with 1 on the border and 0 inside

In [28]:
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
Y = np.zeros((5,5))
Y[[0,-1],:]  = 1
Y[:,[0,-1]]  = 1
print(Y)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
W = np.zeros((3,3))
W = np.pad(W, pad_width=1, mode='constant', constant_values=1)
print(W)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 12. How to add a border (filled with 0's) around an existing array?

In [39]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 13. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [45]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [54]:
3 == 0.3 * 10

True

In [62]:
print(0.3 == (3 * 0.1))
print(0.3 == (3/10))

False
True


In [56]:
6 == 2 * 3

True

In [57]:
0.5 == 0.25 * 2

True

In [58]:
0.5 == 1 * 0.5

True

In [59]:
0.4 == 4 * 0.1

True

#### 15. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [68]:
Z = np.diag(1+np.arange(0,4,1),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [38]:
np.diag((1,2,3,4)).reshape(5,5)

ValueError: cannot reshape array of size 16 into shape (5,5)

In [36]:
np.pad(np.diag((1,2,3,4)), pad_width=1, mode='constant')[0:-1,1:]

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 16. Create a 8x8 matrix and fill it with a checkerboard pattern

In [75]:
Z = np.zeros((4,4),dtype=int)
Z[0::2,::2] = 1
Z[1::2,1::2] = 1
print(Z)

[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


#### 17. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [76]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [40]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 22. Create a checkerboard 8x8 matrix using the tile function

In [122]:
Z = np.tile( np.array([[0,1,0,1],[1,0,1,0]]), (4,2))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [44]:
Z = np.zeros((8,8),dtype=int)
Z[0::2,::2] = 1
Z[1::2,1::2] = 1
print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [45]:
print(np.tile(np.array( [[0,1],[1,0]] ), (8,8)))

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


In [49]:
Z = np.zeros((1,64),dtype=int)
Z[:,1::2] = 1
print(Z.reshape(8,8))

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [124]:
print(np.array([[0,1],[1,0]]))

[[0 1]
 [1 0]]


#### 23. Normalize a 5x5 random matrix

In [52]:
Z = np.array([[1,2],[3,4]])
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [55]:
Z = np.array([[1,2],[3,4]])
Z = (Z - np.mean (Z)) / (np.std(Z) ** 2)
print(Z)

[[-1.2 -0.4]
 [ 0.4  1.2]]


In [54]:
Z = np.array([[1,2],[3,4]])
Z = (Z - np.mean (Z)) / (np.sqrt(np.std (Z)))
print(Z)

[[-1.41861241 -0.4728708 ]
 [ 0.4728708   1.41861241]]


#### 0. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [129]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [132]:
A = [[1,4,1],[4,1,4]]
B = [[-1,4],[4,-1],[-1,4]]
Z = np.dot(A, B)
print(Z)

[[14  4]
 [-4 31]]


In [57]:
A = [[1,4],[4,1],[1,4]]
B = [[-1,4,-1],[4,-1,4]]
print(np.dot(A,B))

[[15  0 15]
 [ 0 15  0]
 [15  0 15]]


In [60]:
A = [[1,-4],[-4,1],[1,-4]]
B = [[1,-4,1],[-4,1,-4]]
print(np.dot(A,B))

[[17 -8 17]
 [-8 17 -8]
 [17 -8 17]]


In [56]:
A = [[1,4,1],[4,1,4]]
B = [[-1,4],[4,-1]]
Z = np.dot(A, B)
print(Z)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [133]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script?
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [134]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [144]:
Z = np.array([3,2,5])
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[3 2 5]
[  27    4 3125]
[ 4  2 16]
[False False False]
[0.+3.j 0.+2.j 0.+5.j]
[3. 2. 5.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 0. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [146]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/lib/python3/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [148]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-0.01523532  3.87246679  6.63786401  3.27693264 -3.56496166  5.50992051
  2.25775441 -7.56499228 -3.52422094  3.74476989]
[-1.  4.  7.  4. -4.  6.  3. -8. -4.  4.]


In [68]:
Z = np.array([-0.01, 3.87, -3.62, 3.27])
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-0.01  3.87 -3.62  3.27]
[-1.  4. -4.  4.]
[-1.  4. -4.  4.]


In [69]:
print(np.round(Z))

[-0.  4. -4.  3.]


In [70]:
print(np.where(Z>=0, np.floor(Z), np.ceil(Z)))

[-0.  3. -3.  3.]


In [67]:
for i in range(0,len(Z)):
    if Z[i]>0:
        Z[i] = np.floor(Z[i])
    if Z[i]<0:
        Z[i] = np.ceil(Z[i])
print(Z)

[-1.  4. -4.  4.]


#### 29. How to find common values between two arrays?

In [73]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[3 9 1 4 5 8 8 0 3 3]
[6 6 7 5 5 6 4 0 8 3]
[0 3 4 5 8]


In [77]:
print(Z1-Z2)
print(Z1^Z2)
print(np.in1d(Z1,Z2))
print(Z1[np.in1d(Z1,Z2)])

[-3  3 -6 -1  0  2  4  0 -5  0]
[ 5 15  6  1  0 14 12  0 11  0]
[ True False False  True  True  True  True  True  True  True]
[3 4 5 8 8 0 3 3]


#### 0. How to ignore all numpy warnings (not recommended)? 

#### 0. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [151]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 30. How to get the dates of yesterday, today and tomorrow?

In [3]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-06-24
2020-06-25
2020-06-26


In [79]:
print(np.datetime64('yesterday'))

ValueError: Error parsing datetime string "yesterday" at position 0

#### 31. How to get all the dates corresponding to the month of July 2016?

In [85]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)
print(np.arange('2016-07', '2016-08', dtype='datetime64[M]'))
print(np.arange('2016-07', '2016-08', dtype='datetime64[W]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']
['2016-07']
['2016-06-30' '2016-07-07' '2016-07-14' '2016-07-21']


#### 32. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [8]:
A = np.ones(2)*1
B = np.ones(2)*2
C = np.ones(2)*3
# print("A : ",A)
# print("B : ",B)
# print("add")
np.add(A,B,out=B)
# print("A : ",A)
# print("B : ",B)
# print("divide")
np.divide(A,2,out=A)
# print("A : ",A)
# print("neg")
np.negative(A,out=A)
# print("A : ",A)
# print("mul")
np.multiply(A,B,out=A)
# print("A : ",A)
# print("B : ",B)

array([-1.5, -1.5])

#### 33. Extract the integer part of a random array of positive numbers using 4 different methods

In [9]:
Z = np.random.uniform(0,10,10)
print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[9.3569347  2.90963981 0.74551071 7.54738336 9.71670822 9.56278454
 7.84262384 1.13068335 9.55021484 7.62474618]
[9. 2. 0. 7. 9. 9. 7. 1. 9. 7.]
[9. 2. 0. 7. 9. 9. 7. 1. 9. 7.]
[9. 2. 0. 7. 9. 9. 7. 1. 9. 7.]
[9 2 0 7 9 9 7 1 9 7]
[9. 2. 0. 7. 9. 9. 7. 1. 9. 7.]


#### 34. Create a 5x5 matrix with row values ranging from 0 to 4

In [86]:
Z = np.zeros((5,5))
print(np.arange(5))
Z += np.arange(5)
print(Z)

[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 35. Consider a generator function that generates 10 integers and use it to build an array

In [91]:
def generate():
    for x in range(10):
        yield x
count = 11
Z = np.fromiter(generate(),dtype=float,count=count)
print(Z)

ValueError: iterator too short

#### 36. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

In [92]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 37. Create a random vector of size 10 and sort it

In [116]:
Z = np.random.randint(0,10,5)
print(Z)
Z.sort()
print(Z)

[5 7 8 5 0]
[0 5 5 7 8]


In [119]:
Z = np.array([5,7,8,5,0])
Z = np.sort(Z)
print(Z)

[0 5 5 7 8]


In [120]:
Z = np.array([5,7,8,5,0])
sort(Z)

NameError: name 'sort' is not defined

In [121]:
Z.np.sort()

AttributeError: 'numpy.ndarray' object has no attribute 'np'

#### 0. How to sum a small array faster than np.sum?

#### 39. Consider two random array A and B, check if they are equal

In [130]:
A = np.array([0,1,0,1])
# B = np.array([[0,1],[0,1]])
B = np.array([0,1,0,0.999999])

# Assuming identical shape of the arrays and a tolerance for the comparison of values
print(np.allclose(A,B))

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
print(np.array_equal(A,B))


True
False


#### 38. Make an array immutable (read-only) 

In [122]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 40. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 

In [132]:
Z = np.random.random((4,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.98881603 1.00019839 0.20208123 1.06303168]
[0.58073972 0.34056249 0.36301274 0.54309676]


#### 41. Create random vector of size 10 and replace the maximum value by 0

In [136]:
Z = np.array([1,2,1,2])
Z[Z.argmax()] = 0
print(Z)

[1 0 1 2]


#### 0. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [139]:
Z = np.zeros((2,2), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,2),
                             np.linspace(0,1,2))
print(Z)

[[(0., 0.) (1., 0.)]
 [(0., 1.) (1., 1.)]]


#### 0. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 42. Print the minimum and maximum representable value for each numpy scalar type 

In [140]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 0. How to print all the values of an array?

In [141]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

#### 45. How to find the closest value (to a given scalar) in a vector?

In [149]:
Z = np.arange(11,16,1)
# v = np.random.uniform(0,10)
v = 12.5
index = (np.abs(Z-v)).argmin()
print(Z)
print(v)
print(Z[index])

[11 12 13 14 15]
12.5
12


In [150]:
Z = np.arange(11,16,1)
# v = np.random.uniform(0,10)
v = 12.3
index = (np.abs(Z-v)).argmin()
print(Z)
print(v)
print(Z[index])

[11 12 13 14 15]
12.3
12


In [151]:
Z = np.arange(11,16,1)
# v = np.random.uniform(0,10)
v = 12.7
index = (np.abs(Z-v)).argmin()
print(Z)
print(v)
print(Z[index])

[11 12 13 14 15]
12.7
13


#### 0. Create a structured array representing a position (x,y) and a color (r,g,b) 

In [157]:
Z = np.zeros(5, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)
print(Z['position'][0])
print(Z['color'][4])

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.))]
(0., 0.)
(0., 0., 0.)


#### 46. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [163]:
Z = np.random.random((5,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
print(X)
print(Y)
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.12262364 0.12752349 0.90857698 0.27425335 0.37787297]]
[[0.70227894 0.38436416 0.05480465 0.94193826 0.24445218]]
[[0.         0.31795254 1.01830526 0.28359859 0.52417321]
 [0.31795254 0.         0.84773464 0.57655748 0.286793  ]
 [1.01830526 0.84773464 0.         1.09058356 0.56357159]
 [0.28359859 0.57655748 1.09058356 0.         0.70514101]
 [0.52417321 0.286793   0.56357159 0.70514101 0.        ]]


In [171]:
X = np.array([[1, 2]])
Y = np.array([[1, 1]])
print(X)
print(Y)
D = (np.sqrt( (X-X.T)**2 + (Y-Y.T)**2))
print(D)

[[1 2]]
[[1 1]]
[[0. 1.]
 [1. 0.]]


#### 0. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [178]:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
print(Y)
Y[:] = Z
print(Y)

[14.404164 64.9028   89.06269  29.622873 55.742863 97.82697   6.733585
 74.29613  99.47971  21.48853 ]
[1097234293 1115803196 1118969881 1106049957 1113520305 1120118633
 1087863175 1117034398 1120335261 1101785218]
[14 64 89 29 55 97  6 74 99 21]


#### 0. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays?

#### 0. Generate a generic 2D Gaussian-like array

In [181]:
X, Y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(X)
print(Y)
print(G)

[[-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]]
[[-1.  -1.  -1.  -1.  -1. ]
 [-0.5 -0.5 -0.5 -0.5 -0.5]
 [ 0.   0.   0.   0.   0. ]
 [ 0.5  0.5  0.5  0.5  0.5]
 [ 1.   1.   1.   1.   1. ]]
[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? 

#### 47. Subtract the mean of each row of a matrix

In [193]:
X = np.array([[1,2],[3,4],[5,6]])
print(X)
print(X.mean(axis=1))
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[1 2]
 [3 4]
 [5 6]]
[1.5 3.5 5.5]
[[-0.5  0.5]
 [-0.5  0.5]
 [-0.5  0.5]]


In [194]:
X = np.array([[1,2],[3,4],[5,6]])
print(X)
print(X.mean(axis=1))
# Recent versions of numpy
Y = X - X.mean(axis=0, keepdims=True)
print(Y)

[[1 2]
 [3 4]
 [5 6]]
[1.5 3.5 5.5]
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


#### 48. How to sort an array by the nth column? 

In [197]:
Z = np.array([[5, 1, 2], [0, 9, 1], [6, 1, 6]])
print(Z)
print(Z[Z[:,1].argsort()])

[[5 1 2]
 [0 9 1]
 [6 1 6]]
[[5 1 2]
 [6 1 6]
 [0 9 1]]


In [203]:
print(Z.T)
print(Z[Z[:,1].argsort()])

[[5 0 6]
 [1 9 1]
 [2 1 6]]
[[5 1 2]
 [6 1 6]
 [0 9 1]]


#### 60. How to tell if a given 2D array has null columns?

#### 49. Find the nearest value from a given value in an array

In [219]:
Z = np.arange(0,0.8,0.1).reshape(2,2,2)
print(Z)
z = 0.65
print(Z.flat[np.abs(Z - z).argmin()])
# print(Z[np.abs(Z - z).argmin()])
# print(m)

[[[0.  0.1]
  [0.2 0.3]]

 [[0.4 0.5]
  [0.6 0.7]]]
0.6000000000000001


#### 0. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

#### 50. Create an array class that has a name attribute

In [229]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "unnamed")

Z = NamedArray(np.arange(10), "array_0_to_9")
print (Z.name)
print (Z.info)
X = NamedArray(np.arange(10))
print (X.name)
print (X.info)

array_0_to_9
unnamed
no name
unnamed


#### 18. 19. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [90]:
Z = np.ones(5)
print(Z)
I = np.random.randint(0,len(Z),5)
print(I)
print(np.bincount(I, minlength=len(Z)))
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1.]
[3 0 0 2 4]
[2 0 1 1 1]
[3. 1. 2. 2. 2.]


In [85]:
x = np.array([1,1,1,2,2,2,5,25,1,1])
unique, counts = np.unique(x, return_counts=True)
print(counts)
print (np.asarray((unique, counts)).T)

[5 3 1 1]
[[ 1  5]
 [ 2  3]
 [ 5  1]
 [25  1]]


In [89]:
Z = np.ones(5)
print(Z)
I = np.random.randint(0,len(Z),5)
print(I)
_,counts = np.unique(I,return_counts=True)
Z += I
print(Z)
Z = np.ones(5)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1.]
[1 4 0 4 1]
[2. 5. 1. 5. 2.]
[2. 3. 1. 1. 3.]


In [92]:
Z = np.ones(5)
print(Z)
I = np.random.randint(0,len(Z),5)
print(I)
# print(np.bincount(I, minlength=len(Z)))
print((Z + np.bincount(I, minlength=len(Z))))
Z = np.ones(5)
np.add.at(Z, I, 1)
print(Z)

[1. 1. 1. 1. 1.]
[3 2 2 1 4]
[1. 2. 3. 2. 2.]
[1. 2. 3. 2. 2.]


In [94]:
Z = np.ones(5)
print(Z)
I = np.random.randint(0,len(Z),5)
print(I)
for i in I:
    Z[i] += 1
print(Z)

[1. 1. 1. 1. 1.]
[1 1 2 2 0]
[2. 3. 3. 1. 1.]


In [106]:
Z = np.ones(5, dtype=int)
print(Z)
I = np.array([3,0,0,2,4])
print(I)
(np.add.at(Z,I,1))
print(Z)
(np.add.at(Z,I,1))
print(Z)

[1 1 1 1 1]
[3 0 0 2 4]
[3 1 2 2 2]
[5 1 3 3 3]


#### 0. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [231]:
X = np.array([1,2,3,4,5,6])
I = np.array([1,3,9,3,4,1])
F = np.bincount(I,X)
print(F)
# F

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 20. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [109]:
w,h = 2,2
I = np.random.randint(1,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))
print(n)
print(I)
print(F)

[1]
1
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[257 257]
 [257 257]]


In [120]:
w,h = 2,2
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*255*255 + I[...,1]*255 +I[...,2]
n = len(np.unique(F))
print(I)
# print(I[...,0])
# print(I[...,1])
# print(I[...,2])
print(F)
print(n)

[[[0 1 1]
  [0 1 0]]

 [[1 0 1]
  [1 1 0]]]
[[  0 255]
 [  2   0]]
3


#### 21. Considering a four dimensions array, how to get sum over the last two axis at once? 

In [114]:
Z = np.ones((3,3))
Z += np.arange(3)
print(Z)
print(Z.sum(axis=(-2,-1)))
print(Z.sum(axis=(-1)))
print(Z.sum(axis=(-2)))
print(Z.sum(axis=1))
print(Z.sum(axis=0))

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
18.0
[6. 6. 6.]
[3. 6. 9.]
[6. 6. 6.]
[3. 6. 9.]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

#### 51. How to get the diagonal of a dot product?

In [233]:
A = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
B = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

print(A)
print(B)

print(np.dot(A,B))

# Slow version
print(np.diag(np.dot(A, B)))

print(A*B.T)

# Fast version
print(np.sum(A * B.T, axis=1))

# Faster version
print(np.einsum("ij,ji->i", A, B))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[ 30  81 150]
[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]
[ 30  81 150]
[ 30  81 150]


#### 52. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [235]:
Z = np.array([1,2,3])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

In [240]:
A = np.ones((2,2,2))
print(A)
B = 2*np.ones((2,2))
print(B)
print(A * B[:,:,None])
print(A*B)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[2. 2.]
 [2. 2.]]
[[[2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]]]
[[[2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]]]


In [241]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B)

ValueError: operands could not be broadcast together with shapes (5,5,3) (5,5) 

#### 53. How to swap two rows of an array?

In [242]:
A = np.arange(9).reshape(3,3)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles 

#### 0. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?

In [243]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [248]:
def moving_average(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(10,20,1)
print(moving_average(Z, 4))

[11.5 12.5 13.5 14.5 15.5 16.5 17.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)